services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app
    ports:
      - "3000:3000"
    depends_on:
      migration:
        condition: service_completed_successfully
    networks:
      - ecommerce-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: ecommerce-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - ecommerce-network

  migration:
    build:
      context: .
      dockerfile: scripts/Dockerfile.migration
    container_name: ecommerce-migration
    env_file:
      - .env
    depends_on:
       mongodb:
         condition: service_healthy
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    name: ecommerce-network

volumes:
  mongodb_data:
    name: mongodb_data