kind: ConfigMap
apiVersion: v1
metadata:
  name: easyshop-configmap
  namespace: easyshop-ns

data:
  MONGODB_URI : mongodb://mongodb-service:27017/easyshop # Database Configuration
  NEXTAUTH_URL : http://a589ecc49c0884d14b339a88d7ce3ece-1729362524.us-east-1.elb.amazonaws.com
  NEXT_PUBLIC_API_URL : http://a589ecc49c0884d14b339a88d7ce3ece-1729362524.us-east-1.elb.amazonaws.com/api




#MONGODB_URI is very important to change. It is the connection string to your MongoDB.
#When testing your application locally using docker compose, the MONGODB_URI should include the name of the mongo service as the host, for example: mongodb://mongodb-service:27017/easyshop

#When deploying your application to a Kubernetes cluster, the MONGODB_URI should include the name of the mongo service as the host which you have defined in stateful set yaml file, for example: mongodb://mongodb-service:27017/easyshop


#change your nextauth url and next public api url to the load balancer url of your kubernetes cluster (easyshop-service). You can find the load balancer url by running the command: kubectl get services -n easyshop-ns