kind: Job
apiVersion: batch/v1

metadata:
  name: data-migration-job
  namespace: easyshop-ns
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation

spec:
  template:
    spec:
      containers:
      - name: migration-job
        image: hiimanshupawar/easyshop-migration:ec86423fc6ff6d99d888297af5aef01277f94161
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: easyshop-configmap
              key: MONGODB_URI
      restartPolicy: OnFailure 